### ISSUE TITLE
  21:59:20.304  ServerScriptService.ServerHandler.Data:92: attempt to index nil with 'Stage'  -  Server - Data:92

### ISSUE THREAD

**Issue by Toxiconl** [PacktPublishing/Coding-Roblox-Games-Made-Easy#2]
Hi,

I read the book en tried to practice with the examples named in the book. Now i try to make the obby example. I tried to retyped the scripts just to understand and learn. But somehow i ran into this error everytime. I downloaded the example scripts (keep them unchanged) and used them but no luck the same error. I also downloaded the example game but received the same error. Please can someone help me with this? It seems to me there is an bug in the code...but im not an expert mabye I just doing something wrong. I'm new to coding.

thanks for the help in advance!

**Comment by ZanderBrumbaugh** [comment]
Do you have API permissions enabled under Game Settings?

**Comment by hanfian** [comment]
> Do you have API permissions enabled under Game Settings?

If it's not this, let us know the exact error you got
