### ISSUE TITLE
Bugs in the code for Chapter 5

### ISSUE THREAD

**Issue by Cflow785** [PacktPublishing/Coding-Roblox-Games-Made-Easy#3]

**Comment by ZanderBrumbaugh** [comment]
Can you please describe what the error is and where it is occurring?

**Comment by Cflow785** [comment]
08:38:25.088  ServerScriptService.ServerHandler.Data:91: attempt to index nil with 'Coins'  -  Server - Data:91

Also the coins do not work when walking through them no so and it does not add to total. The spring potion block does not work either. 
Thanks
Cory Flowers
    On Wednesday, November 10, 2021, 09:24:47 PM CST, ZanderBrumbaugh ***@***.***> wrote:  
 
 


Can you please describe what the error is and where it is occurring?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZanderBrumbaugh** [comment]
Do you have API services enabled under the Game Settings menu?

**Comment by Cflow785** [comment]
Zander, 
That helped, thank you, however now the game is saving the level but not the coins. I am using your demo of the obby to test all this out so I am unsure why it is not saving the coins I am no longer getting an error as before but it is not saving my coins from previous testing sessions. 
Thanks, 
Cory 
    On Thursday, November 11, 2021, 04:03:33 PM CST, ZanderBrumbaugh ***@***.***> wrote:  
 
 


Do you have API services enabled under the Game Settings menu?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
